"""Restore League FK in Match

Revision ID: 0ed2c693904d
Revises: 8c0ebc3029e9
Create Date: 2026-01-04 23:34:12.116229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0ed2c693904d'
down_revision: Union[str, Sequence[str], None] = '8c0ebc3029e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('league_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'match', 'team', ['away_team_id'], ['id'])
    op.create_foreign_key(None, 'match', 'team', ['home_team_id'], ['id'])
    op.create_foreign_key(None, 'match', 'league', ['league_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_column('match', 'league_id')
    # ### end Alembic commands ###
