"""Add xG columns to Match

Revision ID: 8c0ebc3029e9
Revises: efbea53f747a
Create Date: 2026-01-04 19:35:32.337107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c0ebc3029e9'
down_revision: Union[str, Sequence[str], None] = 'efbea53f747a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('xg_home', sa.Float(), nullable=True))
    op.add_column('match', sa.Column('xg_away', sa.Float(), nullable=True))
    op.drop_constraint(op.f('match_league_id_fkey'), 'match', type_='foreignkey')
    op.drop_constraint(op.f('match_away_team_id_fkey'), 'match', type_='foreignkey')
    op.drop_constraint(op.f('match_home_team_id_fkey'), 'match', type_='foreignkey')
    op.drop_column('match', 'league_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('league_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('match_home_team_id_fkey'), 'match', 'team', ['home_team_id'], ['id'])
    op.create_foreign_key(op.f('match_away_team_id_fkey'), 'match', 'team', ['away_team_id'], ['id'])
    op.create_foreign_key(op.f('match_league_id_fkey'), 'match', 'league', ['league_id'], ['id'])
    op.drop_column('match', 'xg_away')
    op.drop_column('match', 'xg_home')
    # ### end Alembic commands ###
