"""add_league_team_match_player_tables

Revision ID: efbea53f747a
Revises: 485d66f92f51
Create Date: 2026-01-02 22:22:29.448041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'efbea53f747a'
down_revision: Union[str, Sequence[str], None] = '485d66f92f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('season', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_league_name'), 'league', ['name'], unique=False)
    op.create_table('team',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stadium', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('league_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_name'), 'team', ['name'], unique=False)
    op.create_table('match',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=False),
    sa.Column('away_goals', sa.Integer(), nullable=False),
    sa.Column('possession_home', sa.Float(), nullable=True),
    sa.Column('possession_away', sa.Float(), nullable=True),
    sa.Column('shots_home', sa.Integer(), nullable=True),
    sa.Column('shots_away', sa.Integer(), nullable=True),
    sa.Column('shots_on_target_home', sa.Integer(), nullable=True),
    sa.Column('shots_on_target_away', sa.Integer(), nullable=True),
    sa.Column('corners_home', sa.Integer(), nullable=True),
    sa.Column('corners_away', sa.Integer(), nullable=True),
    sa.Column('league_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('home_team_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('away_team_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('technical_attributes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('team_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.add_column('user_role', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # op.drop_constraint(op.f('user_role_users_id_fkey'), 'user_role', type_='foreignkey')
    # op.create_foreign_key(None, 'user_role', 'users', ['user_id'], ['id'])
    # op.drop_column('user_role', 'users_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('user_role', sa.Column('users_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # op.drop_constraint(None, 'user_role', type_='foreignkey')
    # op.create_foreign_key(op.f('user_role_users_id_fkey'), 'user_role', 'users', ['users_id'], ['id'])
    # op.drop_column('user_role', 'user_id')
    op.drop_table('player')
    op.drop_table('match')
    op.drop_index(op.f('ix_team_name'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_league_name'), table_name='league')
    op.drop_table('league')
    # ### end Alembic commands ###
